CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    grade VARCHAR(10) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    gender VARCHAR(10) NOT NULL,
    class INT NOT NULL,
    add_line1 VARCHAR(255) NOT NULL,
    add_line2 VARCHAR(255),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    pincode VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);